#ifndef __CHANNEL_H__
#define __CHANNEL_H__

class Channel
{
public:
	/// Constructor
	/// @param channel_id Unique id for this channel generated by Server.
	/// @param parent_id Id of the parent channel, -1 means no parent.
	/// @param channel_name Name of the channel.
	Channel(int channel_id, int parent_id, const std::string& channel_name);
	~Channel();


	/// @brief Returns the name of the channel.
	const std::string& Name() const;

	/// @brief Returns the channels unique ID.
	int Id() const;

private:
	int _id;
	int _parent_id; // Id of the parent channel

	std::string _name;

};


#endif // __CHANNEL_H__
