#ifndef __VOICECHATSERVER_CLIENT_H__
#define __VOICECHATSERVER_CLIENT_H__

#include <QTcpSocket>

#include "shared/common.h"
#include "shared/messagecallbackhandler.h"

class Server;
class ConfigValue;

/// @brief Class representing a user connected to the server.
class User : public QObject
{
	Q_OBJECT;
public:
	/// Constructor
	/// @param user_id Unique identifier for this user generated by Server.
	/// @param socket An open socket for the connection to this user.
	/// @param udp_port The udp port assigned to this user for media streaming.
	User(int user_id, Server* server, QTcpSocket* socket, int udp_port);
	~User();

	/// @brief Sends a message object to this User.
	void SendMessage(const ConfigValue& msg_object);

	/// @brief Returns the name of the user.
	const std::string& Name() const;

	/// @brief Returns the unique ID of the user.
	int Id() const;

	/// @brief Returns the gstreamer destination port for this user.
	int UdpPort() const;

	/// Returns the id of the channel that currently holds the user.
	/// @return Channel id, -1 if currently not in any channel.
	int Channel() const; 

	/// @brief Sets a new channel for this user.
	void SetChannel(int channel_id);

	/// @brief Returns the TCP socket for this user.
	QTcpSocket* Socket();

	uint32_t SSRC() const;

private slots:
	/// @brief The socket disconnected.
	void Disconnected();

	/// @brief Ready to read from the socket.
	void ReadyRead();

private:
	/// @brief Processes a message.
	void ProcessMessage(const std::string& message);

	/// Message callbacks

	/// @brief Reads a hello message from the socket.
	void OnHelloMsg(const ConfigValue& msg_object);

	/// @brief Reads a chat message from the socket.
	void OnChatMsg(const ConfigValue& msg_object);

	/// @brief Called when the user wants to change its channel.
	void OnChangeChannel(const ConfigValue& msg_object);

	/// @brief Called when the user sends its SSRC identifier
	void OnUserSSRC(const ConfigValue& msg_object);

private:
	int _user_id;
	int _channel_id;

	Server* _server;
	QTcpSocket* _socket;

	int _udp_port;
	bool _authed;
	std::string _name;

	uint32_t _ssrc; // SSRC for RTP

	MessageCallbackHandler<User> _callback_handler;
};


#endif // __VOICECHATSERVER_CLIENT_H__
